### ISSUE TITLE
Áxil Quirino: Incremental Development, 3 weeks

### ISSUE THREAD

**Issue by bringmetheaxx** [HackYourFutureBelgium/class-15#103]
> [module repository](https://github.com/bringmetheaxx/TeamFour)

## Study Plan

- [x] Incremental Development

- [x] Git & GitHub

- [x] Command Line Interface

- [x] Writing READMEs

- [x] DevTools and the DOM

- [x] HTML & CSS

- [x] Collaborating on GitHub

- [x] User Stories

**Comment by bringmetheaxx** [comment]
Week 1

- [ ] [Group Issue](https://bringmetheaxx.github.io/TeamFour/)
- [ ] Still working in my homepage


### Check-In

#### I Need Help With:
nothing tbh.

#### What went well?
our group can communicate well with each other. 

#### What went less well?
Long calls without a proper decision. 

#### Lessons Learned
I am working really well with the VS Code.

**Comment by Lizhen2910** [comment]
Hi Axil, thanks for your check-ins. Please join this Sunday 18 April 10:30 AM career skills session on how to provide great feedback.

**Comment by bringmetheaxx** [comment]
## Week 2

- [ ] [Group Issue](https://lauraramirez220612.github.io/TeamFourHYF/)
- [ ] Still working in my homepage


### Check-In

#### I Need Help With:
I think I need to learn how to deal with frustrations of coding, working with GitHub and VS Code. 

#### What went well?
Our group works well together and everybody is helping each other with it's a good thing. 

#### What went less well?
I think we still having some trouble focusing on what should and need to be done. 

#### Lessons Learned
It doesn't need to be perfect, but functional. 
Everyone has their own to do things so I can do it the way I feel more comfortable with.

**Comment by colevandersWands** [comment]
> I think I need to learn how to deal with frustrations of coding, working with GitHub and VS Code.

don't we all.  maybe trick yourself out of frustrating by assuming you'll never understand anything then being surprised by every little progress?

> I think we still having some trouble focusing on what should and need to be done.

classic challenge, prioritizing is not easy especially when you're just learning the material.  Plenty of time to learn this at HYF and noticing already gives you a big head start

**Comment by bringmetheaxx** [comment]
## Week 2

- [ ] [Group Issue](https://lauraramirez220612.github.io/TeamFourHYF/)
- [ ] Still working in my homepage


### Check-In

#### I Need Help With:
I am having a hard time with the reverse engineer, it's more complicated that I would expect. 

#### What went well?
Our team is doing a great work together and I think we can make it work. 

#### What went less well?
We are still having some trouble in the PR's. 

#### Lessons Learned
I am working better with the command line. 

⚠️ Real images of my relation with coding ⚠️ 

![working](https://user-images.githubusercontent.com/77135654/116405141-9adc7300-a82f-11eb-9fe4-c6c258018b4b.gif)

**Comment by colevandersWands** [comment]
> I am having a hard time with the reverse engineer, it's more complicated that I would expect.

@bringmetheaxx , what about it do you find complicated?  Is it writing the code? planning the steps?

> I am working better with the command line.

Just curious, have you been playing the CLI games?

**Comment by bringmetheaxx** [comment]
> @bringmetheaxx , what about it do you find complicated? Is it writing the code? planning the steps?

Writing the code is the most difficult part to me. 

> Just curious, have you been playing the CLI games?

I played a lot. It helped me.
