### ISSUE TITLE
Behavior, Strategy, Implementation, week 1, Sunday Roll Call

### ISSUE THREAD

**Issue by colevandersWands** [HackYourFutureBelgium/class-15#130]
Leave a comment with these two things:

1. A summary of your week using only emojis
2. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by kilicf** [comment]
1. 🤕 🤚 💻 🕛 
2. No place to fall 🍂  I can do that  💪 🛸

**Comment by katsmamina** [comment]
:technologist: :tired_face: :airplane: :belgium: :zany_face: :lotus_position_woman:

**Comment by zehrayelkenci** [comment]
1. :computer:  :upside_down_face: :computer: :slightly_smiling_face: :computer: 
2. Time goes fast  

:new_moon:  :waxing_crescent_moon: :first_quarter_moon:  :moon: :waxing_gibbous_moon: :full_moon:

**Comment by inggritenovaleta** [comment]
1. 🤒 ⏳ 
2. Lots of personal obstacles this week but I believe in myself. You should too 🙌🏼 we can do this 🚀

**Comment by colevandersWands** [comment]
oops, wrong class repo!
