### ISSUE TITLE
bringmetheaxx: UX/UI Design, 2 weeks

### ISSUE THREAD

**Issue by bringmetheaxx** [HackYourFutureBelgium/class-15#149]
[Homepage](https://bringmetheaxx.com/)

### User Experience and User Interfaces
   - [x] Empathy for Developers
   - [x] UX Research, User Interviews & Personas
   - [x] Design Thinking
   - [x] Design Thinking for Developers
   - [x] General
   - [x] User experience (UX)
   - [x] Gestalt
   - [x] Colour
   - [x] Iconography
   - [x] Typography and Fonts
   - [x] Style Guides
   - [x] Accessibility
   - [ ] Imagery and Photography
   - [ ] Illustration
   - [ ] Design inspiration
   - [ ] Free Courses
   - [ ] Figma
   - [ ] UI Kits
   - [ ] More Softwares
   - [ ] Books

### Open Source Software
   - [ ] What is Open Source Software?
   - [ ] Open Source Licenses
   - [x] Codes of Conduct
   - [x] Contributor Guidelines
   - [x] How to Contribute

**Comment by bringmetheaxx** [comment]
Week 1

### Project 
  - [ ] First Interview
  - [ ] Follow-Up Interview
  - [ ] Capture Findings
  - [ ] Define the Problem
  - [ ] Open-Ended Ideation
  - [ ] Partner Feedback
  - [ ] Final Plan
  - [ ] Final Wireframe
  - [ ] Final Feedback

- [ ] [project issue](https://github.com/HackYourFutureBelgium/class-15/issues/144)


### Check-In

#### I Need Help With:
I have awful design skills, the struggle is real. 

#### What went well?
Me and my partner worked well together. 

#### What went less well?
My design skills. 

#### Lessons Learned
A second opinion can change the perspective of things, which can make the homepage I am building better.

**Comment by colevandersWands** [comment]
> I have awful design skills, the struggle is real.

"I have undeveloped design potential, the struggle is real"

> A second opinion can change the perspective of things, which can make the homepage I am building better.

: )

**Comment by bringmetheaxx** [comment]
Week 1

### Project 
  - [ ] Studying
  - [ ] Figma

- [x] [project issue](https://github.com/HackYourFutureBelgium/class-15/issues/144)

### Check-In

#### I Need Help With:
Design skills

#### What went well?
After the interview and the last week process, I have a clear idea of which direction I want to go and what I want to do. 

#### What went less well?
I have two left hands and half of a brain.

#### Lessons Learned
Doing pretty things is hard. 
![reallife](https://user-images.githubusercontent.com/77135654/118019189-03137480-b359-11eb-9680-3c37b4c179eb.gif)

**Comment by colevandersWands** [comment]
> I have two left hands and half of a brain.

![two left feet](https://i.pinimg.com/originals/98/a5/6c/98a56c171daabf37d2158c8382712725.jpg)
