### ISSUE TITLE
Daniel: HYF Precourse - Individual Project

### ISSUE THREAD

**Issue by danielhalasz** [HackYourFutureBelgium/class-15#15]
Daniel's home page

- [x] [repo](https://github.com/danielhalasz/danielhalasz.github.io)
- [x] a great README file
- [x] [live demo](https://danielhalasz.github.io/)
- [x] [many small, well-named commits](https://github.com/danielhalasz/danielhalasz.github.io/commits)

**Comment by colevandersWands** [comment]
@danielhalasz , the most beautiful web page I've ever seen : )  I'm happy to see you're getting the idea of git and github.  You'll get a chance to rebuild this home page in UX/UI Design so no pressure to improve the design right away
