### ISSUE TITLE
RosaMoran: UX/UI, 2 week

### ISSUE THREAD

**Issue by RosaMoran** [HackYourFutureBelgium/class-15#166]
## Study Plan
repo
[RosaMoran](https://github.com/RosaMoran/RosaMoran.github.io) 
### User Experience and User Interfaces

- [x] Empathy for Developers

- [x] UX Research, User Interviews & Personas

- [x] Design Thinking

- [x] Design Thinking for Developers

- [ ] General

- [x] User experience (UX)

- [ ] Gestalt

- [ ] Colour

- [ ] Iconography

- [ ] Typography and Fonts

- [ ] Style Guides

- [ ] Accessibility

- [ ] Imagery and Photography

- [ ] Illustration

- [ ] Design inspiration

- [ ] Free Courses

- [ ] Figma

- [ ] UI Kits

- [ ] More Softwares

- [ ] Books

### Open Source Software

- [ ] What is Open Source Software?

- [ ] Open Source Licenses

- [ ] Codes of Conduct

- [ ] Contributor Guidelines

- [ ] How to Contribute

**Comment by iLienstAr** [comment]
@colevandersWands Rosa
