### ISSUE TITLE
bringmetheaxx: Welcome to JS, 2 weeks 

### ISSUE THREAD

**Issue by bringmetheaxx** [HackYourFutureBelgium/class-15#191]
> [module repository](https://github.com/HackYourFutureBelgium/welcome-to-js)

### Be the Computer

- [x] 🥚 [compute-it](http://compute-it.toxicode.fr/)
- [x] 🐣 [little-dot](http://little-dot.toxicode.fr/)

### What is Programming?

- [x] [CodeAcademy](https://www.codecademy.com/articles/what-is-programming)
- [x]  [The Coding Train](https://www.youtube.com/watch?v=AImF__7FyzM)
- [x] [Practical Introduction to JS](https://shawnr.gitbooks.io/practical-introduction-to-javascript/content/what-is-programming/)

### What is JavaScript?

- [x] [Andrew Mosh](https://www.youtube.com/watch?v=W6NZfCO5SIk) (first 5 minutes)
- [x] [Code School](https://www.youtube.com/watch?v=nItSSTwBvSU)
- [x] [MDN: First Steps](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)
- [ ] [javascript.info](https://javascript.info/intro)
- [x] [Danielle Thé](https://www.youtube.com/watch?v=gT0Lh1eYk78)

### Tutorials
- [x] [sololearn](https://www.sololearn.com/learning/1024): through Conditionals and Loops
- [ ] [javascript.express](https://www.javascript.express/): the chapters that cover Just Enough JavaScript
- [x] [launchcode](https://education.launchcode.org/intro-to-professional-web-dev/index.html): chapters 1 -> 5
- [x] [programiz](https://www.programiz.com/javascript/get-started): through while loops
- [x] [freecodecamp](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/): through for loops. (more advanced)
- [x] [speaking js](http://speakingjs.com/) (online book)
- [x]  [Headfirst JavaScript](https://www.oreilly.com/library/view/head-first-javascript/9781449340124/ch01.html): an outstanding (paid) book for understanding JS and the web. comes with code samples you can run locally

### Reading Code

- [x] ([how do computers read code?](https://www.youtube.com/watch?v=QXjU9qTsYCc))
- [x] [Reading code is harder than writing it](https://trishagee.github.io/presentation/reading_code/)
- [x] [Learn to read the Source, Luke](https://blog.codinghorror.com/learn-to-read-the-source-luke/)
- [x] [Close-Reading Code](https://kylefdoherty.github.io/blog/2014/06/26/close-reading-code/)
- [x] [Read Code Good](https://www.youtube.com/watch?v=mW_xKGUKLpk)
- [x] [How to read code?](https://itnext.io/how-to-read-code-bf478c262932)
- [x] [5 tips](https://medium.com/@smilin.robin/5-tips-on-how-to-read-someone-elses-code-b931b6a059ec)
- [ ] [How to read other people's code](https://selftaughtcoders.com/how-to-quickly-and-effectively-read-other-peoples-code/)
- [ ] [ASCII Pronunciation Rules for Programmers](https://blog.codinghorror.com/ascii-pronunciation-rules-for-programmers/)
- [ ] [JavaScript Glossary](https://www.codecademy.com/articles/glossary-javascript)
- [ ] [How to teach programming (and other things)?](https://www.youtube.com/watch?v=g1ib43q3uXQ&feature=youtu.be&t=1209)
- [ ] Code Reading Clubs - [code-reading.org](https://code-reading.org/)
 
### Just Enough JavaScript

- [x] 00-comments-and-logs
- [x] 01-primitive-values
- [x] 02-operators
- [x] 03-booleans
- [x] 04-strings
- [ ] 05-undefined
- [ ] 06-variables
- [ ] 07-null
- [ ] 08-interactions
- [ ] 09-numbers
- [ ] 10-block-scope
- [ ] 11-conditionals
- [ ] 12-while-loops
- [ ] 13-break-continue
- [ ] 14-for-of-loops

### Describing Programs

- [ ] frogopedia-1.js
- [ ] frogopedia-2.js
- [ ] frogopedia-3.js
- [ ] getting-an-orange.js
- [ ] keep-or-not.js
- [ ] long-string-1.js
- [ ] long-string-2.js
- [ ] long-string-3.js
- [ ] long-string-4.js
- [ ] madlib-1.js
- [ ] madlib-2.js
- [ ] remembery-1.js
- [ ] remembery-2.js
- [ ] emembery-3.js
- [ ] spell-it-1.js
- [ ] spell-it-2.js

### Reading Programs

- [ ] 1-remembery.js
- [ ]  2-madlib.js
- [ ] 3-getting-an-orange.js
- [ ] 4-frogify.js
- [ ] 5-repeat-or-remove-1.js
- [ ] 5-repeat-or-remove-2.js
- [ ] 6-filter-words.js
- [ ]  7-search.js
- [ ] 8-guessing-game.js

**Comment by bringmetheaxx** [comment]
## Week 1

### Check-In

#### I Need Help With:
~I don't even know to be honest.~I am scared of how much things I need to do. 

#### What went well?
I like to learn JS, I think it makes some things easier. 

#### What went less well?
Sometimes I got stuck trying to learn things. 

#### Lessons Learned
If it's working, don't try to much, just accept it. 

![goodplace](https://user-images.githubusercontent.com/77135654/118868311-5307b380-b8e4-11eb-8561-547ea36a11b2.gif)

**Comment by perezrei** [comment]
Hello @bringmetheaxx  I'm trying to read the issues of the whole group to know a little about each one. My advice: 

- [ ] Watch the video from last Sunday, It's in the repo.
- [ ] Study in the repo, Week 1, Before Class, and focus in what you should have studied before last sunday. 
        What is Programming?, What is JavaScript?
        Skim these chapters from ./just-enough-javascript
        Comments and Logs
        guide-tracing.mp4
        Variables
        Conditionals

- [ ] Try to do the exercises of what we studied last sunday (extremely important)
- [ ] Study in the repo, Week 2, Before Class:
- [ ]  Skim these chapters from ./just-enough-javascript
        Break, Continue
        For-of Loops
        Look through the READMEs of
        ./reading-programs
        ./describing-programs
        Try out the "ask me" button if you haven't yet

Maybe you will think it's a lot, but believe me, it is less than all those things that you say you are going to study in this Week & check-in.

Good luck

**Comment by colevandersWands** [comment]
> I am scared of how much things I need to do.

Just focus on 1-2 weeks at a time, everything you learn will build on itself and by the time you look up you'll know more than you expected.  It's only been 5 days, be patient with yourself @bringmetheaxx.

And keep in mind that the JS modules at HYF are very thorough, you don't need to master everything the first time around. You can always go back and review topics when you need them later on

> I like to learn JS, I think it makes some things easier.

it makes things possible!  once you start seeing what can be done with JS I have a feeling you'll take off and make some pretty cool things

**Comment by bringmetheaxx** [comment]
> Hello @bringmetheaxx I'm trying to read the issues of the whole group to know a little about each one. My advice:
> 
>     * [ ]  Watch the video from last Sunday, It's in the repo.
> 
>     * [ ]  Study in the repo, Week 1, Before Class, and focus in what you should have studied before last sunday.
>       What is Programming?, What is JavaScript?
>       Skim these chapters from ./just-enough-javascript
>       Comments and Logs
>       guide-tracing.mp4
>       Variables
>       Conditionals
> 
>     * [ ]  Try to do the exercises of what we studied last sunday (extremely important)
> 
>     * [ ]  Study in the repo, Week 2, Before Class:
> 
>     * [ ]   Skim these chapters from ./just-enough-javascript
>       Break, Continue
>       For-of Loops
>       Look through the READMEs of
>       ./reading-programs
>       ./describing-programs
>       Try out the "ask me" button if you haven't yet
> 
> 
> Maybe you will think it's a lot, but believe me, it is less than all those things that you say you are going to study in this Week & check-in.
> 
> Good luck

Muchísimas gracias, @perezrei

**Comment by bringmetheaxx** [comment]
## Week 1

### Check-In

#### I Need Help With:
It's still a lot and I am trying to learn everything, but it's so confusing sometimes. 

#### What went well?
This week I was able to learn more. 

#### What went less well?
Sometimes I got stuck trying to learn things. (Same as last week)

#### Lessons Learned:
Doing a lot of things at the same time is not the solution sometimes ~always~

P.S: doing the check-in late because I had a collapse and I was taken to the hospital.
