### ISSUE TITLE
Reinaldo Perez, welcome-to-js, 2 weeks.

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-15#194]
> [My repository](https://github.com/perezrei/class-15.git)

## Study Plan

- [ ] Completing all the exercises from the module

#### I Need Help With:
So far I'm good

#### What went well?
Understanding the exercises  with no stress from being out of date in studies. 
Dedicating time to do the exercises.
It's a big satisfaction to complete the exercises applying what we have learned.

#### What went less well?
Nothing so far

#### Lessons Learned
The main lesson learned is that study programming is different from studying some theoretical subject. If you don't practice, success will always be far away. My goal is to finish all the exercises this week before Sunday class

### Sunday Prep Work

- [ ] Break, Continue
- [ ] For-of Loops
- [ ] Describe a program
- [ ] Practice answering questions from the "ask me" button

**Comment by perezrei** [comment]
> [My repository](https://github.com/perezrei/class-15.git)

## Study Plan

- [ ] From today I'll start to practice the exercises of debugging. 

## Week 2

### Check-In

#### I Need Help With:
So far I'm good

#### What went well?
I really focus on JS the past two weeks. I did almost all the exercises, so now I feel more confident.
On the other hand, I must say that I believe that in this class 15 there are more people who participate, and I like that because it is more profitable to study in a group than alone.

#### What went less well?
I think I have to practice more reading code out loud to improve my skills of commenting code.

#### Lessons Learned
I could say that conditionals and loops was something that I had not practiced before so that I could highlight it among other things as lessons learned.

### Sunday Prep Work

- [ ] isolate exercises

**Comment by Lizhen2910** [comment]
I agree @perezrei a nice group dynamic is a good incentive to learning.
