### ISSUE TITLE
Reinaldo Perez, Debugging 4 Weeks

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-15#214]
> [My repository](https://github.com/perezrei/debugging)

## Study Plan

- [x] Integrate
- [x] Isolate Exercises (not all of them of course)

Week 1

- [x] started the exercises

#### I Need Help With:
I'm better than ever now

#### What went well?
Doing the exercises

#### What went less well?
Nothing

#### Lessons Learned
Fixing errors and bugs
breakpoints.js
debugger-statement.js
in-js-tutor.js
in-the-devtools.js
in-vscode-debugger.js

**Comment by perezrei** [comment]
# Week 2

- [x] started the exercises


### Check-In

#### I Need Help With:
I am fine with everything that I have practiced with the exercises.

#### What went well?
I'm really learning through the practice. There is a big difference between what I'm learning in class 15 and class 13-14 but is because now I do the exercises.

#### What went less well?
I wish, like everybody else, to have more hours of study. That's one of my goals. In less than 2 weeks, I'll be studying HYF exclusively. 

#### Lessons Learned
Numbers and NaN
for loops
explicit coercion
let vs. const
numbers/repeat-string
values swaps


#### Sunday Prep Work:
Functions

**Comment by colevandersWands** [comment]
> I wish, like everybody else, to have more hours of study. 

if only!

**Comment by perezrei** [comment]
# Week 3

- [ ] start the exercises


### Check-In

#### I Need Help With:
Nothing you can help me because is a matter of time to study

#### What went well?
Nothing so far with the exercises

#### What went less well?
Yesterday I had my final written exam of french and tomorrow the oral one so, from now on, I'll be free to study just HYF. That's the good thing.

#### Lessons Learned
👎🏻 


#### Sunday Prep Work:

- [ ] isolate: reference vs. value
- [ ] side-effects

**Comment by colevandersWands** [comment]
> Yesterday I had my final written exam of french and tomorrow the oral one so, from now on, I'll be free to study just HYF.

T'is the season!  A lot of your classmates have also lost study time due to language exams.  Do you want to start proposing times in the class channel for a post-language-exam review session?  Tag your coaches so we can make it too

**Comment by perezrei** [comment]
# Week 4

- [ ] finish isolate-exercises


### Check-In

#### I Need Help With:
So far I'm good, actually I feel better than ever with the exercises but still, there's a lot to do.

#### What went well?
For me, it's been a good study week now that I’m dedicated just to study HYF

#### What went less well?
I have not finished all debugging exercises, but I'll keep on doing them.

#### Lessons Learned
I am very satisfied with my improvement (although there is still a lot to practice). If I don't manage something well, it is because I haven't done all the exercises yet.

#### Sunday Prep Work:

- [ ] solution-write-ups

**Comment by perezrei** [comment]
> > Yesterday I had my final written exam of french and tomorrow the oral one so, from now on, I'll be free to study just HYF.
> 
> T'is the season! A lot of your classmates have also lost study time due to language exams. Do you want to start proposing times in the class channel for a post-language-exam review session? Tag your coaches so we can make it too

> My excuses @colevandersWands I had not read this comment. Ok'I like the idea I'm goin to propose that in Slack

**Comment by perezrei** [comment]
@colevandersWands this is just an observation:

I didn't start practicing with the exercises 4 weeks ago in the same order of how they are presented in the module's repo. I was practicing according to each Sunday class, but then I realized that there is something confusing: There are things that we had to practice first (04-value-swaps, 05-explicit-coercion, 06-logical-operators for example) before trying to start with more advanced stuff, like arrays, loops or functions, for example. 

Some of my classmates have given more importance to some topics because we all have decided individually what to study, and it's different from each one. For example, Ekaterina wanted to do "integrate" exercises first than "isolate" and then we were agreed that was the opposite.  I have a suggestion for next classes why don't you enumerate the topics as you do in "isolate" for example, because they are ordered alphabetically and at the beginning, because it's too much information, we try to start in the order they appear in the module repo.

**Comment by samirm00** [comment]
@perezrei  It is OK if you didn't finish all `debugging` exercises  , you can always come back to them  whenever you have time.

**Comment by colevandersWands** [comment]
@perezrei, I tried to suggest a selection and sequence of exercises in the **After Class** part of each week's section in the README.  Do you mean something more specific than this? Or should i make it more clear that this is not just a suggestion?
