### ISSUE TITLE
Behavior, Strategy, Implementation, week 1, Sunday 4 July 2021 Roll Call

### ISSUE THREAD

**Issue by Lizhen2910** [HackYourFutureBelgium/class-15#226]
Leave a comment with these two things:

1. A summary of your week using only emojis
2. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by WalterAlvar** [comment]
🏃🏾‍♂️🍜⚽🖌️🎶💻🖨️🖱️🧪📝

**Comment by deepa-thomas** [comment]
:computer::thumbsup::writing_hand::coffee::house:


<br class="Apple-interchange-newline">

**Comment by Mika215** [comment]
💻:sun_behind_large_cloud:

**Comment by Moamin-AbuEwaida** [comment]
:star_struck::star_struck::star_struck:
:robot::robot::robot::robot::robot:
:bike::bike::bike::bike:
:eyes::eyes::eyes::eyes::eyes:
:computer::computer::computer:
:soccer:  :belgium:  :it:    :soccer:

**Comment by rayanejsilva** [comment]
👀👩🏻‍💻⏰☕️🌻

**Comment by perezrei** [comment]
1. ⌨️ 💻 📓 🔢 🧪 👨🏻‍💻

**Comment by danielhalasz** [comment]
💻 🌞 💯 🌴 🏊

**Comment by Dabrytskaya** [comment]
☺️💻💻🙈😉

**Comment by TatsianaRud** [comment]
☺️💻💻

**Comment by firity** [comment]
💻 💻 🏃🏾‍♀️ 🏃🏾‍♀️ 👍🏾 😫

**Comment by hserdogan94** [comment]
🛩️⏳✈️

**Comment by Hajir-pro** [comment]
😐🌧🌧☕️

**Comment by RosaMoran** [comment]
😊🥰🏃‍♀️🏃‍♀️💻💻💻⚽️⚽️⚽️

**Comment by Senait-coding** [comment]
💻 👩🏼‍🎓 💻 👩‍👦 🤔 💻 😟

**Comment by yildiztugba** [comment]
🌴💻☕️👍

**Comment by Osimef849** [comment]
🛡️ 🙏 📚  💻 🖱️ 
😃 🌴

**Comment by Maria2811-code** [comment]
🔢 🔢 👍🏻 💯

**Comment by lauraramirez220612** [comment]
👓🖥️🤔➿🧭⚽🎶📌🙂👍
