### ISSUE TITLE
Reinaldo Perez: Behavior-Strategy-Implementation, 3 Weeks

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-15#233]
> [behavior-strategy-implementation repository](https://github.com/perezrei/behavior-strategy-implementation)

## Study Plan

Week 1

- [x] started the exercises

#### I Need Help With:
I'm ok. I understand the goal of this module. It's really fun, to practice and learning from comparing different approaches in the same exercise.

#### What went well?
If I say something different, I would be lying to myself.  For this half of the first week, I wanted to feel more comfortable with the four possible strategies to approach repeating a string and the language features I could implement, and I played a bit with Edabit too. 
From tomorrow, I will start filling my folder of write-ups.

#### What went less well?
Nothing really.

#### Lessons Learned

- The mechanic of the module
- Sample tests
- Some new JS built-in functions

### Sunday Prep Work

- [x] Function design
- [x] About testing

**Comment by samirm00** [comment]
@perezrei  So glad , you find the module interesting and fun , all thanks to @colevandersWands  who spent a lot of time and hard work to makes it easy and fun.

**Comment by perezrei** [comment]
That's so true @samirm00

**Comment by colevandersWands** [comment]
> I wanted to feel more comfortable with the four possible strategies to approach repeating a string 

@perezrei , those are not the only 4 strategies!  Just the 4 I thought of when writing the README.  can you find another?

**Comment by perezrei** [comment]
Ok  I got it @colevandersWands. Well, right now I only can think in the simplest one using math operations.

**Comment by perezrei** [comment]
Using arrow function it's not another approach, It's just another syntax for functions, am I right?

**Comment by colevandersWands** [comment]
> Using arrow function it's not another approach, It's just another syntax for functions, am I right?

for now, yes.  If you start getting fancy and try to use `this`, they're different.  but we won't cover that until after the final project

**Comment by perezrei** [comment]
👍🏻

**Comment by perezrei** [comment]
> [behavior-strategy-implementation repository](https://github.com/perezrei/behavior-strategy-implementation)

## Study Plan

Week 2

- [ ] started the exercises


### Check-In

#### I Need Help With:
Nothing in particular.

#### What went well?
Practicing exercises from debugging and behavior-estrategy-implementation modules.

#### What went less well?
Everything ok but the secondary effects of the vaccine 🤒 

#### Lessons Learned

- [ ] array-methods

### Sunday Prep Work

- [ ] practice-code-review
- [ ] linting

**Comment by perezrei** [comment]
> [behavior-strategy-implementation repository](https://github.com/perezrei/behavior-strategy-implementation)

## Study Plan

Week 3

- [ ] started the exercises


### Check-In

#### I Need Help With:
Although it should be a thing of the past I have not been able to resolve Github related issues after Thursday.

#### What went well?
It's been a little funny this week. I chose `split-object` exercises because everyone else was doing the first ones and it looked to me more challenging. Once I started my solution exercise it took me one day to finish it but, after all, it felt good learning from ES Lint. It was cool. I thougth I was going to do the 5 exercises before sunday but...

#### What went less well?
After I finished the solution, I pushed it to the group's fork and I could see my branch but not my files. 
I worked from a cloned of Daniel's fork (the group fork), like somebody told me, and not from a fork of Daniel's, so I think it was a mistake.

I looked for help with some of my classmates trying to make a call but I think they were too busy this week because I didn't had a feedback.

My second mistake, according to me, is that I did not looked for help from you @colevandersWands  or anyone else outside the group, maybe because I thought I could solve it easily. At the end, I'm still struggling with it. 

Few minutes ago I just deleted my cloned after saving my files, and forked Daniel's repo to clone it and paste the files again to make a Pull Request from my fork but now I see that Daniel deleted, I think by mistake, the split-object file in master branch. I have to solve this today and try to review someone's else solution because tomorrow is my last day to start sudying for sunday's class. 

Finally It's a bit dissapointing how the week ended for me although the lesson was learned.

#### Lessons Learned

- Formatting and linting code from CLI

### Sunday Prep Work

- [ ] The DOM and Event Listener
- [ ] function-roles
- [ ] ES-5 vs ES-6
- [ ] stepped
- [ ] separated

**Comment by perezrei** [comment]
Sometimes I don't bother other people with things that I'm supposed to know because I like to re study them, but I know to that time is gold, and the content is huge, so I should change that thoughts.

**Comment by perezrei** [comment]
@colevandersWands the drama is over 😄. I solved the issue between VS Code and GitHub. I always use CLI but this time I used some interface in VS Code which did something different from I expected.

**Comment by colevandersWands** [comment]
> it felt good learning from ES Lint.

: )  

> Finally It's a bit dissapointing how the week ended for me although the lesson was learned.

git and branch problems are not a distraction at all!  Part of this week was to refresh all that before Separation of Concerns
