### ISSUE TITLE
Firewyni: Individual Project 

### ISSUE THREAD

**Issue by firity** [HackYourFutureBelgium/class-15#25]
- [x] [repo](https://github.com/firity/firity.github.io )
- [x] a great README file
- [x] [live demo](https://firity.github.io/)
- [x] [many small, well-named commits](https://github.com/firity/firity.github.io/commits)

**Comment by colevandersWands** [comment]
@firity , the individual project home page should be [written with HTML & CSS](https://github.com/hackyourfuturebelgium/precourse#individual-project_.  it doesn't need to be fancy - a single small `index.html` is enough.  I'm putting your issue into Needs Revision, you can let me know when you've finished by moving the issue back into Ready for Review.

Don't worry about finishing this before Sunday, you can take your time over the next week

**Comment by firity** [comment]
@colevandersWands okey thanks

**Comment by firity** [comment]
Hello @colevandersWands I add my home page to my individual project  it is not finished because i want to add more.
Can you please check it.Thanks

**Comment by colevandersWands** [comment]
Looking good @firity!  Something you can work on in the next weeks is writing commit messages that describe the changes you made, this will make more sense once you start working together and need to understand what changes everyone is making. 

Keep it up 💪

**Comment by firity** [comment]
@colevandersWands  okey  i will try my best.
Thank you
