### ISSUE TITLE
Senait: HYF Precourse 

### ISSUE THREAD

**Issue by Senait-coding** [HackYourFutureBelgium/class-15#26]
- [x] [repo](https://github.com/Senait-coding/Senait-coding.github.io)
- [x] a great README file
- [x] [live demo](https://senait-coding.github.io/)
- [x] [many small, well-named commits](https://github.com/Senait-coding/Senait-coding.github.io/commits/main)

**Comment by colevandersWands** [comment]
Hello @Senait-coding, it's hard to look over your work when I can't find it!  Can you update the links in this issue so they open to your project?

**Comment by Senait-coding** [comment]
> Hello @Senait-coding, it's hard to look over your work when I can't find it! Can you update the links in this issue so they open to your project?

@colevandersWands Hello, sorry I forgot to update the links, now . I just updated now, hope it you find it now:)Thank you

**Comment by colevandersWands** [comment]
@Senait-coding , could you drop your issue back into Ready for Review? then i'll take a look

**Comment by Senait-coding** [comment]
> @Senait-coding , could you drop your issue back into Ready for Review? then i'll take a look

@colevandersWands , ok ,Done. Thank you

**Comment by colevandersWands** [comment]
@Senait-coding , besides some code formatting issues in `style.css` it looks good to me!  I'm moving your issue to Done and you can reformat the CSS when you get a chance

**Comment by Senait-coding** [comment]
> @Senait-coding , besides some code formatting issues in `style.css` it looks good to me! I'm moving your issue to Done and you can reformat the CSS when you get a chance

@colevandersWands ok I will, thank you
