### ISSUE TITLE
Reinaldo Perez: separation-of-concerns, 3 Weeks

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-15#260]
> [separation-of-concerns](https://github.com/perezrei/separation-of-concerns)

## Study Plan

- [x] function-roles
- [x] isolate: all of it
- [x] integrate: 1 & 2
- [x] stepped
- [x] separated
- [x] magic-variables: it's just 2 examples
- [x] dom-manipulation: the exercises are pretty short
- [x] listeners-and-handlers: 4 exercises

 # Week 1

#### I Need Help With:
I'm good for now. I like this module

#### What went well?
The exercises of isolate

#### What went less well?
Nothing

### Sunday Prep Work

- [x] refactoring
- [x] reverse-engineering

**Comment by perezrei** [comment]
# Week 2

### Check-In

#### I Need Help With:
I'm good.

#### What went well?
Studying in groups the exercises of reverse-engineering  has been great

#### What went less well?
No time yet to check word-list and week 3 before class

#### Lessons Learned

- function roles
- refactoring
- integrate
- reverse-ingeneering
- 

### Sunday Prep Work

- [ ] rendering-data
- [ ] testing-components

**Comment by perezrei** [comment]
# Week 3

### Check-In

#### I Need Help With:
I'm good with the group project.

#### What went well?
Communication with the group and the support of @bermarte have been great.

#### What went less well?
 Nothing really

#### Lessons Learned
Collaborating in a more complicated (for us)  project is challenging and a new experience

### Sunday Prep Work

state:

- [ ] What is state
- [ ] function-roles
- [ ] separated examples
- [ ] planning with state and components

**Comment by colevandersWands** [comment]
> Collaborating in a more complicated (for us) project is challenging and a new experience

🏄🏄🏄🏄🏄🏄

**Comment by perezrei** [comment]
Closing Issue
