### ISSUE TITLE
Reinaldo Perez Architecture 4 Weeks

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-15#288]
> [architecture repository](https://github.com/perezrei/architecture)

## Study Plan

Week 1

#### What went well?
This week, I learned more about collaborating, about git and GitHub, than about JavaScript. I learn every day, that's the most important, and for that part I feel good.

#### What went less well?
I am really disappointed in myself and the group for not having finished the project. We all contributed to the fact that the project was not successfully completed by having established rules and not having complied with them. There is no excuse, but there are reasons that each member of the group must analyze on their own. 

#### Lessons Learned
Organization, commitment and respect for the project I believe are crucial to its success. The rest, the code, is something we are learning, and it might be harder for some than others, but at the end of the day, help is always there through classmates and coaches.

### Sunday Prep Work

**Comment by perezrei** [comment]
Updating my last comment.

**Comment by samirm00** [comment]
@perezrei  building a project takes time and hard work. Don't worry if you didn't finish the project , you still can work on it later.
