### ISSUE TITLE
rayanejsilva: HYF Precourse - Individual Project

### ISSUE THREAD

**Issue by rayanejsilva** [HackYourFutureBelgium/class-15#29]
### Personal home page project

The aim of the individual project is to learn how to develop a personal home page using HTML and CSS.

- [x] [repo](https://github.com/rayanejsilva/rayanejsilva.github.io)
- [x] a great README file
- [x] [live demo](https://rayanejsilva.github.io/)
- [x] [many small, well-named commits](https://github.com/rayanejsilva/rayanejsilva.github.io/commits/main)

**Comment by colevandersWands** [comment]
very nice!  Plenty of commits with nice names, well-formatted code, and plenty of semantic elements 💪
