### ISSUE TITLE
link is broken because of file name capitalization

### ISSUE THREAD

**Issue by colevandersWands** [HackYourFutureBelgium/class-15#30]
@danielhalasz I missed this in our review, GitHub is picky about capital letters in file names.  You made your file name `danielHalasz.md` but your username is `danielhalasz`, because of this the bio link in your [README card](https://github.com/HackYourFutureBelgium/class-15#daniel) doesn't work.

Could you open a new pull request to change the file name to `danielhalasz.md`?

**Comment by danielhalasz** [comment]
done, thank you
