### ISSUE TITLE
Reinaldo Perez Asynchronous-Programming 3 Weeks

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-15#323]
## Study Plan

- [x] browser/the event loop
- [ ] browser/isolate
- [x] browser/promistaurant
- [ ] browser/api calls
- [ ] browser/fetch and render
- [ ] node/commonjs modules
- [ ] node/process argv
- [ ] node/file system
- [ ] node/command line applications
- [x] callbacks
- [x] promises
- [x] async

# Week 1 / Week 2

#### I Need Help With:
Having spent 9 days of travel was good for the soul, but bad for the studies. I missed the first class of this module, but reading the repository a lot and watching a lot of videos strengthens the concept. So far I have had no trouble understanding the module.
#### What went well?
There are still many concepts to strengthen, but I am very clear about what event loop means, the difference between synchronous and asynchronous programming and the concepts of callbacks, promises and async. 
Interesting, venturing into Node.js.
I need another day to consolidate other concepts and start with the exercises.
#### What went less well?
Besides not attending the class of the first week and not having studied the first 4 days of that week, there has been no other issue so far.
#### Lessons Learned
Timeouts and intervals
sync vs async
promises

### Sunday Prep Work

- [ ] fetch
- [ ] API's

**Comment by colevandersWands** [comment]
good for the 👻 !
