### ISSUE TITLE
Tugba: HYF Precourse - Individual Project

### ISSUE THREAD

**Issue by yildiztugba** [HackYourFutureBelgium/class-15#35]
Develop a home page for yourself using HTML & CSS.

- [x] [repo](https://github.com/yildiztugba/yildiztugba.github.io)
- [x] a great README file
- [x] [live demo](https://yildiztugba.github.io/)
- [x] [many small, well-named commits](https://github.com/yildiztugba/yildiztugba.github.io/commits/)

**Comment by colevandersWands** [comment]
@yildiztugba , can you fix the links in your issue so they open to your home page?  it's hard to review your site when I can't find it!

**Comment by yildiztugba** [comment]
@colevandersWands I fixed the links, moved to ready for review. thank you.
