### ISSUE TITLE
Jose Tomas: Individual Project.

### ISSUE THREAD

**Issue by JTLiberona** [HackYourFutureBelgium/class-15#40]
Jose Tomas: project lead and repository owner.

Application of HTML and CSS.

- [x] [repo](https://github.com/JTliberona/JTLiberona.github.io)
- [x] a great README file
- [x] [live demo](https://jtliberona.github.io/)
- [x] [many small, well-named commits](https://github.com/JTLiberona/ice-breaker/commits)

**Comment by colevandersWands** [comment]
@JTLiberona looks you're understanding git and github.  Some clear commits, and the page is deployed 💪.  

Like you say in your README: plenty of time to make it prettier in the coming months
