### ISSUE TITLE
Class 15_3: HYF Precourse - Group Project

### ISSUE THREAD

**Issue by WalterAlvar** [HackYourFutureBelgium/class-15#43]
# This is the "Get to know me" Project of Class 15_3 :
Here we perform our very first practice into _Pull Request_ and _Merge_ to create together a file about us and our own origins, background and expectations. 

https://github.com/WalterAlvar/GetToKnowYouGN3

## List of members:
@Osimef849 
@Hajir-pro 
@SerkanDemir86 
@Maria2811-code 
@RosaMoran
@WalterAlvar _repository owner_

- [x] [repo](https://github.com/WalterAlvar/GetToKnowYouGN3)
- [x] [many small, well-named commits](https://github.com/WalterAlvar/GetToKnowYouGN3/commits/main)
- [x] a nice README and one file per group member
- [x] [one pull requests for each group member](https://github.com/WalterAlvar/GetToKnowYouGN3/pulls?q=is%3Apr+is%3Aclosed)

**Comment by colevandersWands** [comment]
Looks like you made plenty of good mistakes in here, that's great!

**Comment by WalterAlvar** [comment]
Yes it is, we have been bussy learning this workflow. Thanks
