### ISSUE TITLE
Class 15_2: HYF Precourse - Group Project

### ISSUE THREAD

**Issue by firity** [HackYourFutureBelgium/class-15#44]
## Class 15 Group 2 Memberes 

- @Dabrytskaya
- @Yildiztugba
- @Firewyni
- @Deepa-thomas
- @Hserdogan94

- [x] [repo](https://github.com/firity/class15_2.github.io)
- [x] [many small, well-named commits](https://github.com/firity/class15_2.github.io/commits)
- [x] a nice README and one file per group member
- [x] [one pull requests for each group member](https://github.com/firity/class15_2.github.io/pulls)**

**Comment by firity** [comment]
- [ ] [repo](https://github.com/_/_)
- [ ] [many small, well-named commits](https://github.com/_/_/commits)
- [ ] a nice README and one file per group member
- [ ] [one pull requests for each group member](https://github.com/_/_/pulls)

**Comment by colevandersWands** [comment]
good teamwork!  You'll do great in the next module

**Comment by firity** [comment]
@colevandersWands thank you
