### ISSUE TITLE
Class 15_4: HYF Precourse - Group Project

### ISSUE THREAD

**Issue by danielhalasz** [HackYourFutureBelgium/class-15#45]
# Let's Hack Our Future

The members of **TeamFour** are:

- [@lauraramirez220612]
- [@Senait-coding]
- [@TatsianaRud]
- [@bringmetheaxx]
- [@Moamin-AbuEwaida]
- [@danielhalasz]

HackYourFutureBelgium, 2021

:rocket:

- [x] [repo](https://github.com/danielhalasz/class15_4.github.io)
- [x] [many small, well-named commits](https://github.com/danielhalasz/class15_4.github.io/commits)
- [x] a nice README and one file per group member
- [x] [one pull requests for each group member](https://github.com/danielhalasz/class15_4.github.io/pulls)

**Comment by lauraramirez220612** [comment]
Hi Daniel,  my profile is updated.  I am trying to finish the coding.

**Comment by danielhalasz** [comment]
1 more bio to fully complete, otherwise ready for review

**Comment by colevandersWands** [comment]
Well done!  Pull requests, commits, it's all a step in the right direction.

**Comment by colevandersWands** [comment]
Your repo was missing one group member's PR, it's better to check with everyone before submitting.  If you're running late or having trouble finishing the project you can let us know with a mention or on Slack and we'll help out.

We'd rather see you working well together and not finishing on time than rushing through to get something in.  Group projects succeed together! 🧑‍🤝‍🧑

**Comment by Moamin-AbuEwaida** [comment]
Noted @colevandersWands :+1:

**Comment by danielhalasz** [comment]
@bringmetheaxx how is it going, do you need help with the pull request?

**Comment by bringmetheaxx** [comment]
> @bringmetheaxx how is it going, do you need help with the pull request?

I already did the pull request and it's closed now. I think we are actually finished now. 
https://github.com/danielhalasz/class15_4.github.io/pull/7

**Comment by danielhalasz** [comment]
@bringmetheaxx well I am not sure what was going on, but we are not done. You were supposed to issue a pull request from your fork to my repository at  danielhalasz / class15_4.github.io, so that I can review and merge it.. at the moment I do not see your .md file in our group repo (https://github.com/danielhalasz/class15_4.github.io).. so I can not add a link to it either in the group repo's readme.md.. UPDATE: anyway after reopening the issue and merging it, now your .md has appeared among the files.. so I added a link to it now.. so we are now done :)

**Comment by colevandersWands** [comment]
💯
