### ISSUE TITLE
Katia Dabrytskaya: Individual Project

### ISSUE THREAD

**Issue by Dabrytskaya** [HackYourFutureBelgium/class-15#47]
Katia Dabrytskaya: project lead and repository owner.

Personal page 

- [x] [repo](https://github.com/Dabrytskaya/dabrytskaya.github.io)
- [x] a great README file
- [x] [live demo](https://dabrytskaya.github.io/)
- [x] [many small, well-named commits](https://github.com/Dabrytskaya/dabrytskaya.github.io/commits)

**Comment by colevandersWands** [comment]
@Dabrytskaya , looks good! Plenty of small commits and a live demo.  

Something you can work on in the coming weeks is naming your commits with messages that describe what changes you made.  You'll quickly see why this is helpful when the group project begins.
