### ISSUE TITLE
Deepa Thomas: Individual Project

### ISSUE THREAD

**Issue by deepa-thomas** [HackYourFutureBelgium/class-15#51]
Deepa Thomas

Develop a home page for yourself using HTML & CSS.

- [x] [repo](https://github.com/deepa-thomas/deepa-thomas.github.io)
- [x] a great README file
- [x] [live demo](https://deepa-thomas.github.io/)
- [x] [many small, well-named commits](https://github.com/deepa-thomas/deepa-thomas.github.io/commits/main)

**Comment by colevandersWands** [comment]
👋  @deepa-thomas , the code and website good!  My only comment would be to use commit messages that describe what you changed.  Plenty of time to practice that with the group projects
